export enum keys {
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',
  GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS',
  GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_VALID_MANAGERS_SUCCESS = 'GET_VALID_MANAGERS_SUCCESS'
}